### ISSUE TITLE
Test failure with `-D_GLIBCXX_ASSERTIONS` with 4.8.1 (4.8 was fine)

### ISSUE THREAD

**Issue by thesamesam** [ccache/ccache#1288]
### How to reproduce ###

1. Build ccache-4.8.1 with GCC 13 and `-D_GLIBCXX_ASSERTIONS` (apply https://github.com/ccache/ccache/pull/1287 first)
2. Run test suite

### Actual behavior ###

Note that this almost certainly needs `-D_GLIBCXX_ASSERTIONS` to reproduce.

Running tests with GCC 13 when packaging ccache-4.8.1 up for Gentoo, I got the following:
```
1/46 Testing: unittest
1/46 Test: unittest
Command: "/var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1_build/unittest/unittest"
Directory: /var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1_build/unittest
"unittest" start time: May 20 05:33 BST
Output:
----------------------------------------------------------
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:724: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp [], _Dp>::operator[](std::size_t) const [with _Tp = unsigned char; _Dp = std::default_delete<unsigned char []>; typename std::add_lvalue_reference<_Tp>::type = unsigned char&; std::size_t = long unsigned int]: Assertion 'get() != pointer()' failed.
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
/var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1/unittest/test_util_file.cpp:144:
TEST CASE:  util::read_file_part
  util::Bytes

/var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1/unittest/test_util_file.cpp:144: FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal

===============================================================================
/var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1/unittest/test_util_file.cpp:144:
TEST CASE:  util::read_file_part

DEEPEST SUBCASE STACK REACHED (DIFFERENT FROM THE CURRENT ONE):
  util::Bytes

===============================================================================
[doctest] test cases:  171 |  170 passed | 1 failed | 26 skipped
[doctest] assertions: 1822 | 1822 passed | 0 failed |
[doctest] Status: FAILURE!
<end of output>
Test time =   0.50 sec
----------------------------------------------------------
Test Failed.
"unittest" end time: May 20 05:33 BST
"unittest" time elapsed: 00:00:00
----------------------------------------------------------
```

If I run it under gdb as `gdb --args ./unittest`:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:724: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp [], _Dp>::operator[](std::size_t) const [with _Tp = unsigned char; _Dp = std::default_delete<unsigned char []>; typename std::add_lvalue_reference<_Tp>::type = unsigned char&; std::size_t = long unsigned int]: Assertion 'get() != pointer()' failed.

Thread 1 "unittest" received signal SIGABRT, Aborted.
0x00007ffff7c8524c in ?? () from /usr/lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7c8524c in ?? () from /usr/lib64/libc.so.6
#1  0x00007ffff7c34ad6 in raise () from /usr/lib64/libc.so.6
#2  0x00007ffff7c1d877 in abort () from /usr/lib64/libc.so.6
#3  0x000055555582e07f in std::__glibcxx_assert_fail (file=file@entry=0x5555558bbb40 "/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/unique_ptr.h", line=line@entry=724,
    function=function@entry=0x5555558bba28 "typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp [], _Dp>::operator[](std::size_t) const [with _Tp = unsigned char; _Dp = std::default_delete<unsigned char []>; typename std::add_lval"..., condition=condition@entry=0x5555558bb2e7 "get() != pointer()")
    at /var/tmp/portage/sys-devel/gcc-13.1.1_p20230513/work/gcc-13-20230513/libstdc++-v3/src/c++11/debug.cc:61
#4  0x000055555575439f in std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >::operator[] (this=0x7fffffffda60, __i=0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:722
#5  std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >::operator[] (__i=<optimized out>, this=0x7fffffffda60)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:722
#6  util::Bytes::operator[] (pos=<optimized out>, this=0x7fffffffda60) at /var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1/src/util/Bytes.hpp:130
#7  util::read_file_part<util::Bytes> (path=..., pos=pos@entry=0, count=count@entry=0) at /var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1/src/util/file.cpp:234
#8  0x000055555569a34b in DOCTEST_ANON_FUNC_8 () at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/basic_string.tcc:238
#9  0x00005555555d6eaa in doctest::Context::run (this=this@entry=0x7fffffffe198) at /var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1/src/third_party/doctest.h:7007
#10 0x00005555555b4384 in main (argc=1, argv=0x7fffffffe348) at /var/tmp/portage/dev-util/ccache-4.8.1/work/ccache-4.8.1/unittest/main.cpp:45
```

so.. I think this is actually a bug in doctest which we're just seeing now because of c61690fd7850029c0bba5223f99df4eb05c4293d? 

### Expected behavior ###

All tests pass.

### Environment ###

ccache version 4.8.1. ccache 4.8 passes.

Gentoo, amd64, Linux 6.1.28, tests were run on a tmpfs but main filesystem is ZFS.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

It's a a bug in a code path that will only ever trigger in a unit case. Will fix.
